# From https://github.com/conda-incubator/setup-miniconda/blob/master/etc/example-environment.yml
name: sheepgut
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2=2.17
  - samtools >= 1.7
  - numpy
  - cython
  - checkm-genome
  - pip
  - pip:
      - -r pip-requirements.txt
