# Copied from Pleuk's workflow, which was in turn based on Empress' workflows
# and the GitHub tutorial (https://docs.github.com/en/actions/quickstart)
name: SheepGut Analysis Code CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
            environment-file: environment.yml
            activate-environment: sheepgut
            python-version: 3.7

      - name: Run tests
        run: conda run -n sheepgut make test
